name: jiran_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  getwidget: ^4.0.0
  dio: ^5.0.3
  flutter_easyloading: ^3.0.5
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  http: ^1.1.0
  webview_flutter: ^4.4.1
  url_launcher: ^6.2.1
  logger: 2.0.2+1
  flutter_dotenv: 5.1.0
  flutter_masked_text2: 0.9.1
  auto_size_text: 3.0.0
  carousel_slider: 4.2.1
  qr_flutter: 4.1.0
  dotenv: 4.2.0
  flutter_stripe: 10.1.1
  flutter_inappwebview: 6.0.0
  crypto: 3.0.3
  permission_handler: 11.3.1
  mobile_scanner: 5.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.2.0
  json_serializable: ^6.7.1
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/images/icon.jpeg
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/json/
    - .env
  uses-material-design: true

