name: jiran_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  getwidget: ^4.0.0
  dio: ^5.0.3
  flutter_easyloading: ^3.0.5
  flutter_firebase_chat_core: ^1.6.7
  firebase_core: ^2.20.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  firebase_auth: ^4.12.0
  http: ^1.1.0
  webview_flutter: ^4.4.1
  url_launcher: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  logger: 2.0.2+1
  flutter_dotenv: 5.1.0
  flutter_masked_text2: 0.9.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/logo.jpeg
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/
    - .env
  uses-material-design: true

